### ISSUE TITLE
Any tutorials?

### ISSUE THREAD

**Issue by DBlaNQ** [lubien/popura#21]
I melted my brain on this and i still can't understand how to use it. Can anyone help?

**Comment by lubien** [comment]
Maybe I can help you. 

First of all, are you used to JS? How about NodeJS?

**Comment by DBlaNQ** [comment]
Yes I am used to them but I am not good with arrays and objects. Those two are really hard for me that's why I asked here

**Comment by lubien** [comment]
Ok first of all I assume you're working inside a npm repo.

After installing (`npm install --save popura`)  it you should put on some file the following:

```js
const popura = require('popura') // 1
const client = popura('username', 'pass') // 2

client.getAnimeList() // 3
  .then(res => console.log(res)) // 4
  .catch(err => console.log(err)) // 4
```

[**1**] just requires it from node_modules. 

[**2**] instances popura. MyAnimeList requires login and password in almost everything so my library centers around that requirement too.

[**3**] Example usage of the object. You may use many others like `addAnime`, `updateAnime`.

[**4**] Since my library works with Promises all methods are `then`ables. If you don't know what Promises are, I suggest you to take a time to read about them as they are a big part of the current state of JavaScript.

About arrays:

If you're having trouble manipulating data that comes from my library as they all are arrays then I suggest you to give a break to this library and get into some readings and/or videos where you can learn more on how to manipulate them. 

Arrays (and any kind of collection data structure) are a core feature in many programming languages and you should learn them carefully.

**Comment by DBlaNQ** [comment]
I did try to get the titile of the anime with .searchAnime and it said can't display empty message. does .searchAnime work with .then as well?

**Comment by lubien** [comment]
you can check what kind of response types are in the README of this repo.

![screenshot_2018-01-10_17-32-57](https://user-images.githubusercontent.com/9121359/34794106-5fe61f02-f62c-11e7-9599-fcffc21751a7.png)

This means it's a thenable.

```js
client.searchAnime().then(animes => {
  // do stuff
})
```

**Comment by DBlaNQ** [comment]
Thanks for the help. Will try it out and tell you the results.

**Comment by DBlaNQ** [comment]
Can popura work with Discord.js?

**Comment by lubien** [comment]
I see no problem with both of them working together. Ultimately it's up to you to try

**Comment by DBlaNQ** [comment]
Because I have problems with the message.channel.send. It displays can't send an empty message. Thought They can't work together

**Comment by lubien** [comment]
Can you paste here an example on how you're using it?

**Comment by DBlaNQ** [comment]
```
animel.searchAnimes(name = args[1]).then(animes => {
            message.channel.send(animes.episodes)
        })```

**Comment by DBlaNQ** [comment]
That's how i first tried it. Then i tried doing the .map and .join it displayed an undefined function

**Comment by lubien** [comment]
It's too less for me to to reason about. Can you expand the code?

**Comment by DBlaNQ** [comment]
First attempt
```
animel.searchAnimes(name = args[1]).then(animes => {
            message.channel.send(animes.episodes)
        })
```
secund attempt
```
 animel.searchAnimes(name = args[1]).then(animes => {
            var AnAry = [animel.episodes]
            var mapedAr = AnAry.map()
            mapedAr.join(" : ")
            message.channel.send(mapedAr)
        })
```
Output: TypeError: Undefined is not a function
I know i'm doing something wrong just by looking at the code but i can't figure out whats the problem

**Comment by lubien** [comment]
```js
 animel.searchAnimes(name = args[1]).then(animes => { //1
            var AnAry = [animel.episodes] // 2
            var mapedAr = AnAry.map() // 3
            mapedAr.join(" : ") // 4
            message.channel.send(mapedAr) // 5
        })
```

[**1**] No need to declare a var `name` just use ` animel.searchAnimes(args[1])`.

[**2**] Np how you completely ignore the `animes` variable from the line 1 and use `animel.episodes` which is incorrect as it doesn't have any episode.

[**3**] anyArray.map expect a function inside parens (that's why the error happens)

[**4**] You join but don't save anywhere so this line is useless

[**5**] as line 3 bugs the code won't get in here

Most of the errors come from lack o JS knowledge. I strongly recommend you to study a little bit more before going any further otherwise any simple thing will look hard.

Trust me, I've used to do JS without properly learning it and my life was harder than should be. Once I've started learning it for real things went better.

**Comment by DBlaNQ** [comment]
okay guess i am gonna go learn some js again. thanks for the help tho much respect for that

**Comment by lubien** [comment]
If I may.

freecodecamp.com is where I started. Exercise based learning.

Then http://eloquentjavascript.net/ since I think wrote knowledge is valuable and the author gives us good insights on how the language works and how to use it.

After that is basically training.

If you wan't more advanced knowledge on the language then https://github.com/getify/You-Dont-Know-JS

I'm going to close this issue but feel free to contact me via telegram @lubien (preferred) or email.
