### ISSUE TITLE
Get times user added episodes?

### ISSUE THREAD

**Issue by NoobDoesMC** [lubien/popura#24]
Is it possible to extract a list of episodes the user watched and when?

**Comment by lubien** [comment]
As mentioned in #23:

> This wrapper only supports data given by MAL's XML API. All supported data is on this repo's README.

![image](https://user-images.githubusercontent.com/9121359/36100535-51353b78-0fe5-11e8-9d2b-370d8d59a155.png)

You can get the **number of watched episodes**, when the user **started** to watch the anime and when it **finished**.

For more information about the support of the API you can also refer to [the official docs](https://myanimelist.net/modules.php?go=api).

**Comment by NoobDoesMC** [comment]
But it's not possible to get times individual episodes were watched using this API?

**Comment by lubien** [comment]
> But it's not possible to get times individual episodes were watched using this API?

As you can **read in [README](https://github.com/lubien/popura)** and in **[the docs](https://myanimelist.net/modules.php?go=api)**, there's no model for individual episodes.

But you can assume:

1. Given an anime with N episodes
2. User already completed it
3. User rewatched M times.

The view count for each episode would be `1 + M`.

1. What if the user is currently watching?

![image](https://user-images.githubusercontent.com/9121359/36122755-4de5e262-1029-11e8-86be-ca1c6d7d8792.png)

Then the view count is 1 for all episodes with number <= `my_watched_episodes`. Zero otherwise.

2. What if the user is currently **re**watching?

![image](https://user-images.githubusercontent.com/9121359/36122820-8b337260-1029-11e8-89d7-3c66674127e3.png)

Then the count is 1 + M + 1 if the episode number is <= `my_rewatched_ep`. 1 + M otherwise.

I really encourage you to look into these[¹](https://myanimelist.net/modules.php?go=api) [²](https://github.com/lubien/popura/issues/24#issuecomment-365081183) sources before asking.
